### ISSUE TITLE
win10 wsl can't use "open in integrate terminal"

### ISSUE THREAD

**Issue by imgwho** [formulahendry/vscode-terminal#9]
i use vscode 1.14.1, win10 15063.483,terminal 0.0.8
and set the default terminal like this: 
"terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe"
and then i find when i touch "open in integrate terminal" like this :
```
cd "e:\practice\jirengu\senior-8"
wuv@wuv:/mnt/e/practice/jirengu$ cd "e:\practice\jirengu\senior-8"
bash: cd: e:\practice\jirengu\senior-8: No such file or directory
wuv@wuv:/mnt/e/practice/jirengu$
```
how i go setting to solve this problem?
is it because of the directory "/" && "\"?

**Comment by formulahendry** [comment]
@imgwho This issue has been fixed, please try the latest version.

**Comment by imgwho** [comment]
oops...the same problem persists....
![as the picture shows](https://i.loli.net/2017/07/22/5973614b3be4d.png)
Thank you very much for your reply!
